package part02;

import java.util.List;
import java.util.stream.Stream;

public class StringStreams {

    // List of words generated by ChatGPT, (GPT-3.5)
    public static final List<String> words = List.of("Algorithm", "Variable", "Function", "Class", "Object", "Array",
            "Loop", "Conditional", "Inheritance", "Polymorphism", "Abstraction", "Encapsulation", "Compiler",
            "Interpreter", "Debugger", "Framework", "Library", "Version Control", "Database", "API", "Bug", "Testing",
            "Debugging", "Syntax", "Java", "Python", "C++", "JavaScript", "HTML", "CSS");

    /**
     * Returns a stream of all the words in the list.
     *
     * @return a Stream of all words
     */
    public Stream<String> streamAllWords() {
        return null;
    }

    /**
     * Returns a stream of words that start with the specified substring.
     *
     * @param substring the substring to filter by
     * @return a Stream of words starting with the given substring
     */
    public Stream<String> streamWordsStartingWith(String substring) {
        return null;
    }

    /**
     * Returns a stream of words that include the specified substring.
     *
     * @param substring the substring to filter by
     * @return a Stream of words including the given substring
     */
    public Stream<String> streamWordsIncludingSubstring(String substring) {
        return null;
    }

    /**
     * Returns a stream of words in uppercase.
     *
     * @return a Stream of words in uppercase
     */
    public Stream<String> streamWordsInUppercase() {
        return null;
    }

    /**
     * Returns a stream of words in lowercase.
     *
     * @return a Stream of words in lowercase
     */
    public Stream<String> streamWordsInLowercase() {
        return null;
    }

    /**
     * Returns a stream of words using the FizzBuzz pattern.
     *
     * @return a Stream of words in the FizzBuzz pattern
     */
    public Stream<String> fizzBuzz() {
        return null;
    }
}
